# The primary role types are referenced by RP Rules, and were specified based on head admin input.
# Do not create new ones without discussion.
# You probably want a Subtype instead, anyway. Use the datafield in MindRoleComponent

# Any new primary role types must be listed in RoleTypes.xml

- type: roleType
  id: Neutral
  name: role-type-crew-aligned-name
  color: '#eeeeee'

- type: roleType
  id: SoloAntagonist
  name: role-type-solo-antagonist-name
  color: '#d82000'

- type: roleType
  id: TeamAntagonist
  name: role-type-team-antagonist-name
  color: '#d82000'

- type: roleType
  id: FreeAgent
  name: role-type-free-agent-name
  color: '#ffff00'

- type: roleType
  id: Familiar
  name: role-type-familiar-name
  color: '#6495ed'

- type: roleType
  id: Silicon
  name: role-type-silicon-name
  color: '#6495ed'

- type: roleType
  id: SiliconAntagonist
  name: role-type-silicon-antagonist-name
  color: '#c832e6'

