- type: entity
  id: BaseMindRole
  name: Mind Role
  description: Mind Role entity
  abstract: true
  components:
  - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
  - type: MindRole
    antag: true

#Observer
- type: entity
  parent: BaseMindRole
  id: MindRoleObserver
  name: Observer Role
  components:
  - type: ObserverRole

#Ghost Roles
- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleNeutral
  name: Ghost Role
  components:
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleFamiliar
  name: Ghost Role (Familiar)
  components:
  - type: MindRole
    roleType: Familiar
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleFreeAgent
  name: Ghost Role (Free Agent)
  components:
  - type: MindRole
    roleType: FreeAgent
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleSilicon
  name: Ghost Role (Silicon)
  components:
  - type: MindRole
    roleType: Silicon
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleSiliconAntagonist
  name: Ghost Role (Silicon Antagonist)
  components:
  - type: MindRole
    roleType: SiliconAntagonist
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleSoloAntagonist
  name: Ghost Role (Solo Antagonist)
  components:
  - type: MindRole
    roleType: SoloAntagonist
  - type: GhostRoleMarkerRole

- type: entity
  parent: BaseMindRole
  id: MindRoleGhostRoleTeamAntagonist
  name: Ghost Role (Team Antagonist)
  components:
  - type: MindRole
    roleType: TeamAntagonist
  - type: GhostRoleMarkerRole



# The Job MindRole holds the mob's Job prototype
- type: entity
  parent: BaseMindRole
  id: MindRoleJob
  name: Job Role
#  description:
  # MindRoleComponent.JobPrototype is filled by SharedJobSystem

# Silicon
- type: entity
  parent: BaseMindRole
  id: MindRoleSiliconBrain
  name: Borg Brain Role
  components:
  - type: MindRole
    roleType: Silicon
  - type: SiliconBrainRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSubvertedSilicon
  name: Subverted Silicon Role
  description:
  components:
  - type: MindRole
    antagPrototype: SubvertedSilicon
    roleType: SiliconAntagonist
    subtype: rule-subtype-subverted
  - type: SubvertedSiliconRole

# Dragon
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleDragon
  name: Dragon Role
  components:
  - type: MindRole
    antagPrototype: Dragon
    roleType: TeamAntagonist
    subtype: role-subtype-dragon
    exclusiveAntag: true
  - type: DragonRole
  - type: RoleBriefing
    briefing: dragon-role-briefing

# Ninja
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNinja
  name: Space Ninja Role
  components:
  - type: MindRole
    antagPrototype: SpaceNinja
    roleType: SoloAntagonist
    subtype: role-subtype-ninja
    exclusiveAntag: true
  - type: NinjaRole

# Nukies
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNukeops
  name: Nukeops Operative Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-nukie
    exclusiveAntag: true
    antagPrototype: Nukeops
  - type: NukeopsRole

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsMedic
  name: Nukeops Medic Role
  components:
  - type: MindRole
    antagPrototype: NukeopsMedic

- type: entity
  parent: MindRoleNukeops
  id: MindRoleNukeopsCommander
  name: Nukeops Commander Role
  components:
  - type: MindRole
    antagPrototype: NukeopsCommander

# Revolutionaries
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleHeadRevolutionary
  name: Head Revolutionary Role
  components:
  - type: MindRole
    antagPrototype: HeadRev
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-head-revolutionary
  - type: RevolutionaryRole

- type: entity
  parent: MindRoleHeadRevolutionary
  id: MindRoleRevolutionary
  name: Revolutionary Role
  components:
  - type: MindRole
    antagPrototype: Rev
    subtype: role-subtype-revolutionary

# Survivors (Wizard)
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSurvivor
  name: Survivor Role
  components:
  - type: MindRole
    antagPrototype: Survivor
    roleType: FreeAgent
  - type: SurvivorRole

# Thief
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleThief
  name: Thief Role
  components:
  - type: MindRole
    antagPrototype: Thief
    roleType: SoloAntagonist
    subtype: role-subtype-thief
  - type: ThiefRole

# Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTraitor
  name: Traitor Role
  components:
  - type: MindRole
    antagPrototype: Traitor
    exclusiveAntag: true
    roleType: SoloAntagonist
    subtype: role-subtype-traitor
  - type: TraitorRole

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorSleeper
  name: Sleeper Agent Role
  components:
  - type: MindRole
    antagPrototype: TraitorSleeper

- type: entity
  parent: MindRoleTraitor
  id: MindRoleTraitorReinforcement
  name: Syndicate Reinforcement Role
  components:
    - type: MindRole
      roleType: TeamAntagonist
      subtype: role-subtype-traitor-reinforcement

# Wizards
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleWizard
  name: Wizard Role
  #  description: these are all commented out
  components:
  - type: MindRole
    antagPrototype: Wizard
    exclusiveAntag: true
    roleType: SoloAntagonist
  - type: WizardRole

# Zombie Squad
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleInitialInfected
  name: Initial Infected Role
  components:
  - type: MindRole
    antagPrototype: InitialInfected
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-initial-infected
  - type: InitialInfectedRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleZombie
  name: Zombie Role
  components:
  - type: MindRole
    antagPrototype: Zombie
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-zombie
  - type: ZombieRole
